### ISSUE TITLE
"Header 1" headers don't appear in table of contents

### ISSUE THREAD

**Issue by DeerTears** [chrismaltby/gb-studio-site#36]
This may be entirely intentional on your part, I can try to write future docs around this, but I'm now trying to make it easier to split up longer pages by using larger headers. I can't find a current docs page that uses header 1, but I noticed this was the case when I made a pull request and Netlify showed me the results of it.

Here's a screenshot from my Netlify preview where I use a single heading ``# Actor Properties`` to make a new section:
![image](https://user-images.githubusercontent.com/47726614/94839147-77516700-03cb-11eb-9179-39a24b393790.png)
It's absent

I could always just not use header 1, and find some way to make what I'm writing even more concise to avoid the issue of long pages. I don't wanna scare off new users, but I also want to make sure people know everything that's useful, and anything that's important but not explained out of the box.

**Comment by chrismaltby** [comment]
Hi @DeerTears it's actually intentional as the h1 element for the entire page is set it in docs template 
https://github.com/chrismaltby/gb-studio-site/blob/9e2f23132960dfaa9b40994d35fd039122b309fe/themes/gbstudio/layouts/docs/single.html#L13 by using the `title` front matter that appears in the top of each markdown file

```md
---
title: "Scripting Events"
draft: false
next: "/docs/custom-events"
nextTitle: "Custom Events"
---
```

I think for [accessibility reasons](https://webaim.org/projects/screenreadersurvey7/#heading) each page should only have a single h1, with each subsection being a h2/h3/h4 so might need to switch some of these headers to be one level deeper. It might make the styles not look so great but I can tidy those up if needed.

**Comment by DeerTears** [comment]
Alright, I figured something like that was the reason. I'll stick to how the other pages do it, thanks for the info.

I might eventually ask to have heading sizes altered but I'm not sure what I'd want with that just yet. I also wanna consider if I should add new pages instead of make the existing pages deeper and more verbose. Stuff like hardware limits, maybe even splitting up the scripting events into different pages based on the gamemodes that use them.
